sudo: false
language: erlang
notifications:
  email: false

otp_release:
  - 18.0
  - 18.3
  - 19.0
  - 19.3
  - 20.0
  - 20.3
  - 21.0
  - 21.3
  - 22.0
  - 22.3

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - export PATH=$PWD:$PATH

script:
  - rebar3 clean
  - rebar3 get-deps
  - rebar3 eunit
  - rebar3 ct
  - rebar3 compile

cache:
  directories:
    - .pulserl-cache