version: '3.2'

services:

  pulsar:
    image: apachepulsar/pulsar:2.5.2
    ports:
      - "6650:6650"
    networks:
      - pulsar
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py ../../pulsar/conf/standalone.conf
      && bin/pulsar standalone"

networks:
  pulsar:
    driver: bridge
